name: TPToggle
main: Zeao\Main
version: 0.0.3
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10]
load: STARTUP
author: Zeao
description: Teleport toggle (/tp)
website: Not showing.
commands:
 tptoggle:
  description: toggles /tp
  permission: tptoggle.command.tptoggle
  default: false
